studentmanager/urls.py
from django.contrib import admin
from django.urls import path
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userinfo/list/', views.user_list),
    path('userinfo/add/', views.user_add),
    path('userinfo/<int:nid>/delete/', views.user_delete),
    path('userinfo/<int:nid>/edit/', views.user_edit),
]

login/models.py
from django.db import models


# Create your models here.


class Department(models.Model):
    """部门表"""
    department_name = models.CharField(max_length=64, verbose_name='部门名称')


class UserInfo(models.Model):
    """用户表"""
    user_name = models.CharField(max_length=32, verbose_name="用户登录名")
    user_pwd = models.CharField(max_length=64, verbose_name="用户密码")
    # 创建帐号状态元组
    state_choices = (
        (1, "启用"),
        (2, "禁用"),
    )
    user_state = models.SmallIntegerField(verbose_name="帐号状态", choices=state_choices)

login/views.py
from django.shortcuts import render, redirect
from login import models
from django import forms


# Create your views here.
def user_list(request):
    """ 用户列表 """
    data_list = models.UserInfo.objects.all()
    return render(request, "user_list.html", {'data_list': data_list})


class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo1
        fields = ["user_name", "user_pwd", "user_state"]
        # widgets = {
        #     "user_name": forms.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}),
        #     "user_pwd": forms.TextInput(attrs={"class": "form-control", "placeholder": "密码"}),
        #     "user_state": forms.Select(attrs={"class": "form-control"})
        #
        # }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}


def user_add(request):
    """添加用户信息"""
    # 获取前台表单填写的数据
    if request.method == 'GET':
        form = UserForm()
        return render(request, "user_add.html", {"form": form})

    # 以post提交的数据
    form = UserForm(data=request.POST)
    if form.is_valid():
        # 数据合法 保存到数据库
        print(form.cleaned_data)
        form.save()
        return redirect("/userinfo/list/")
    else:
        # 校验失败 显示错误信息
        return render(request, "user_add.html", {"form": form})
    #  context = {
    #      "state_choice": models.UserInfo.state_choices
    #  }
    # if request.method == 'GET':
    #     return render(request, "user_add.html", context)
    # user_name = request.POST.get("name")
    # user_pwd = request.POST.get("pwd")
    # user_state = request.POST.get("state")
    # # 将获取的数据添加到数据库
    # models.UserInfo.objects.create(user_name=user_name, user_pwd=user_pwd, user_state=user_state)
    # # 重定向到用户列表界面
    # return redirect("/userinfo/list")


# 删除用户信息
def user_delete(request, nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/userinfo/list")


    # nid = request.GET.get("nid")
    # models.UserInfo.objects.filter(id=nid).delete()
    # return redirect("/userinfo/list")


# 编辑用户信息
def user_edit(request, nid):
    if request.method == 'GET':
        row_obj = models.UserInfo.objects.filter(id=nid).first()
        form = UserForm(instance=row_obj)
        return render(request, "user_edit.html", {"form":form})

    row_obj=models.UserInfo.objects.filter(id=nid).first()
    form = UserForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect("/userinfo/list/")
    else:
        return render(request, "user_edit.html",{"form": form})

    # 根据nid获取当前行数据
    # if request.method == "GET":
    #     row_obj = models.UserInfo.objects.filter(id=nid).first()
    #     return render(request, "user_edit.html", {'row_obj': row_obj})
    # name = request.POST.get("name")
    # pwd = request.POST.get("pwd")
    # # pwds = request.POST.get("pwds")
    #
    # models.UserInfo.objects.filter(id=nid).update(user_name=name, user_pwd=pwd, user_state=1)
    # return redirect("/userinfo/list")

login/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>

<!--导航条 -->
<div class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <img src="/login/static/img/alogo5.png">
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="/userinfo/list/">用户添加</a></li>
                <li><a href="#">Link</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">注销</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">个人信息 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div>
    {% block content %}
    {% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

login/templates/user_add.html
{% extends "layout.html" %}
{% block title %}
    <title>新增用户</title>
{% endblock %}

{% block content %}
<div>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建用户信息 </h3>
            </div>
            <div class="panel-body">

                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
{#                        <label for="exampleInputEmail1">用户名：</label>#}
                        {{ form.user_name.label }}:{{ form.user_name }}
                        <span style="color: red">{{ form.user_name.errors }}</span>
{#                        <input type="text" class="form-control" name="name" placeholder="用户名">#}
                    </div>
                    <div class="form-group">
{#                        <label for="exampleInputPassword1">密 码:</label>#}
                        {{ form.user_pwd.label }}:{{ form.user_pwd }}
                        <span style="color: red">{{ form.user_pwd.errors }}</span>
{#                        <input type="password" class="form-control" name = 'pwd' placeholder="密码">#}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">再次确认密码</label>
                        <input type="password" class="form-control"  placeholder="确认密码">
                    </div>
                    <div class="form-group">
{#                        <label for="exampleInputPassword1" >帐号状态：</label>#}
                        {{ form.user_state.label }}:{{ form.user_state }}
                        <span style="color: red">{{ form.user_state.errors }}</span>
{#                        <select class="form-control" name="state">#}
{#                            {% for item in state_choice  %}#}
{#                            <option value={{ item.0 }}>{{ item.1 }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
                    </div>

                    <button type="submit" class="btn btn-default">提交注册</button>
                </form>


            </div>
        </div>
    </div>
</div>
{% endblock %}

login/templates/user_edit.html
{% extends "layout.html" %}

{% block title %}
    <title>编辑用户</title>
{% endblock %}

{% block content %}
<div>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 修改用户信息 </h3>
            </div>
            <div class="panel-body">

                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
{#                        <label for="exampleInputEmail1">用户名：</label>#}
                        {{ form.user_name.label }}:{{ form.user_name }}
                        <span style="color: red">{{ form.user_name.errors }}</span>
{#                        <input type="text" class="form-control" name="name" placeholder="用户名">#}
                    </div>
                    <div class="form-group">
{#                        <label for="exampleInputPassword1">密 码:</label>#}
                        {{ form.user_pwd.label }}:{{ form.user_pwd }}
                        <span style="color: red">{{ form.user_pwd.errors }}</span>
{#                        <input type="password" class="form-control" name = 'pwd' placeholder="密码">#}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">再次确认密码</label>
                        <input type="password" class="form-control"  placeholder="确认密码">
                    </div>
                    <div class="form-group">
{#                        <label for="exampleInputPassword1" >帐号状态：</label>#}
                        {{ form.user_state.label }}:{{ form.user_state }}
                        <span style="color: red">{{ form.user_state.errors }}</span>
{#                        <select class="form-control" name="state">#}
{#                            {% for item in state_choice  %}#}
{#                            <option value={{ item.0 }}>{{ item.1 }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
                    </div>

                    <button type="submit" class="btn btn-default">确认修改</button>
                </form>


            </div>
        </div>
    </div>
</div>
{% endblock %}



















{#{% block content %}#}
{#<div>#}
{#    <div class="container">#}
{#        <div class="panel panel-default">#}
{#            <div class="panel-heading">#}
{#                <h3 class="panel-title"> 修改用户信息 </h3>#}
{#            </div>#}
{#            <div class="panel-body">#}
{##}
{#                <form method="post">#}
{#                    {% csrf_token %}#}
{#                    <div class="form-group">#}
{#                        <label for="exampleInputEmail1">用户名：</label>#}
{#                        <input type="text" class="form-control" name="name" placeholder="用户名" value="{{ row_obj.user_name }}">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <label for="exampleInputPassword1">密码</label>#}
{#                        <input type="password" class="form-control" name = 'pwd' placeholder="密码" value="{{ row_obj.user_pwd }}">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <label for="exampleInputPassword1">再次确认密码</label>#}
{#                        <input type="password" class="form-control" name="pwds" placeholder="确认密码" value="{{ row_obj.user_pwd }}">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <label for="exampleInputPassword1" >帐号状态：</label>#}
{#                        <select class="form-control" name = 'state' value="{{ row_obj.user_state }}">#}
{#                            <option value="1">启用</option>#}
{#                            <option value="2">禁用</option>#}
{#                        </select>#}
{#                    </div>#}
{##}
{#                    <button type="submit" class="btn btn-default">提交</button>#}
{#                </form>#}
{##}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}

login/templates/user_list.html
{% extends "layout.html" %}

{% block title %}
    <title>用户列表</title>
{% endblock %}

{% block content %}
<!--按钮 -->
<div>
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-info" href="/userinfo/add/" >
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新增用户
            </a>
        </div>
        <!--面板-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表</div>
            <table class="table table-bordered">
                <thead0>
                <tr>
                    <th>序号</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>帐号状态</th>
                    <th>操作</th>
                </tr>
                </thead0>
                <tbody>
                {% for obj in data_list %}
                <tr>
                    <th scope="row">{{ obj.id}}</th>
                    <td>{{ obj.user_name }}</td>
                    <td>{{ obj.user_pwd }}</td>
                    <td>{{ obj.get_user_state_display}}</td>
                    <td>
                        <a class="btn btn-primary" value="编辑" href="/userinfo/{{ obj.id }}/edit/">编辑</a>
                        <a class="btn btn-danger" value="删除" href="/userinfo/delete/?nid={{ obj.id }}">删除</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
{% endblock %}